### ISSUE TITLE
Incompatible types during json unmarshalling

### ISSUE THREAD

**Issue by wendigo** [andygrunwald/megos#1]
I'm wondering why couple of fields on the struct (like activated_slaves https://github.com/andygrunwald/megos/blob/master/types.go#L10) are declared as integers while in mesos they are declared as doubles (https://github.com/apache/mesos/blob/837a13f3b8912f3bc847afecff7bfd06536414aa/src/master/master.hpp#L1214)

Using go 1.5.1 querying cluster state panic'ed every single time due to unmarshalling error. I've patched megos locally and it runs flawlessly on mesos 0.25.0 and go 1.5.1.

From go 1.5 changelog:

> The encoding/json package now returns an UnmarshalTypeError if a JSON value is not appropriate for the target variable or component to which it is being unmarshaled.

I can send you over some nice PR :)

**Comment by andygrunwald** [comment]
Thanks for this issue @wendigo.
Nice finding.

> I can send you over some nice PR :)
I would love to see one!

**Comment by andygrunwald** [comment]
@wendigo Can i support you here?

**Comment by andygrunwald** [comment]
@wendigo I merged https://github.com/andygrunwald/megos/pull/4 from @fpgeek a minute ago.
He created the compatibility to v0.25.x
Can you test the new master branch if your case is working now?

**Comment by andygrunwald** [comment]
This was already fixed in https://github.com/andygrunwald/megos/commit/62cffd3ef9a58efa965d4fee15dbc09a9afb3f62
I tested this library against Mesos v0.26.0 and it works.

Thanks for reporting @wendigo
