### ISSUE TITLE
json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by bobrik** [andygrunwald/megos#6]
Mesos slave attributes are not necessary strings:

```json
      {
        "rack": 106,
        "type": "storage"
      }
```

This causes megos to fail on state deserialization:

```
json: cannot unmarshal number into Go value of type string
```

https://github.com/mesosphere/marathon/issues/1711

**Comment by andygrunwald** [comment]
Thx @bobrik
Will try to fix it this evening or at the weekend.
Can you provide a complete json response from a slave state?
Are you referring to a 0.28 Mesos installation?

**Comment by andygrunwald** [comment]
Thank you Ivan!
Fixed and backed by unit tests.
